# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5955c2e005e94bbedf76a11c4e3e5b77a9b76c96f38175a0563de8c9188013dd8e50265504f2bb3a288e35b0329334cc1f57e9d5e7cbae344562ede84b7a84

test:
  secret_key_base: e39671e1f1f09b82315fd6244d7753149f1d645b3166651380381c7ca917c2db5c959872fa4c4c83f1092c36034f9265bb061f32ddc2014a4e0db4417cf3a02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
